latent_dim: 128
datasets: ['tissuemnist', 'octmnist', 'organamnist']
max_epochs: 100
batch_size: 512
kl_coeff: 0.00025
lr: 0.005
checkpoint_dir: results/checkpoints/vae
log_dir: results/logs
model: cvae